// 本文件由 scripts/build-rn-themes.mjs 从 packages/themes/tokens.css 生成 —— 不要手改。
// 改主题请改 tokens.css，然后跑：node scripts/build-rn-themes.mjs

export type ThemeId = "swiss" | "brutal" | "clay" | "kawaii" | "mecha" | "midnight" | "memphis" | "glass";
export type RnTokens = { colors: Record<string, string>; nums: Record<string, number>; misc: Record<string, unknown> };
export type ThemeMeta = { id: ThemeId; name: string; desc: string; swatch: string[] };

export const DEFAULT_THEME: ThemeId = "swiss";

export const THEME_META: ThemeMeta[] = [
  {
    "id": "swiss",
    "name": "瑞士极简",
    "desc": "白纸黑字 · 专业工具（默认）",
    "swatch": [
      "#F1F3F5",
      "#0F172A",
      "#047857",
      "#FFFFFF"
    ]
  },
  {
    "id": "brutal",
    "name": "新粗野",
    "desc": "黑边硬投影 · 荧光黄",
    "swatch": [
      "#F4F1EA",
      "#0A0A0A",
      "#FFE94A",
      "#2F6BFF"
    ]
  },
  {
    "id": "clay",
    "name": "柔和黏土",
    "desc": "暖奶油 · 大圆角软弹",
    "swatch": [
      "#F6EFE6",
      "#15803D",
      "#FDBCB4",
      "#6D5BD0"
    ]
  },
  {
    "id": "kawaii",
    "name": "卡通粉",
    "desc": "少女心 · 圆润可爱",
    "swatch": [
      "#FFF1F6",
      "#FF6FA5",
      "#8B5CF6",
      "#FFD1E3"
    ]
  },
  {
    "id": "mecha",
    "name": "机甲 HUD",
    "desc": "深色霓虹 · 切角科技感",
    "swatch": [
      "#070B12",
      "#00E5FF",
      "#FFB020",
      "#22E08A"
    ]
  },
  {
    "id": "midnight",
    "name": "暗夜护眼",
    "desc": "深色暖琥珀 · 关灯看",
    "swatch": [
      "#0F172A",
      "#F0B44A",
      "#7C6BF5",
      "#4ADE80"
    ]
  },
  {
    "id": "memphis",
    "name": "孟菲斯 80s",
    "desc": "多彩几何 · 潮流张扬",
    "swatch": [
      "#FFFDF6",
      "#FF71CE",
      "#FFCE5C",
      "#86CCCA"
    ]
  },
  {
    "id": "glass",
    "name": "极光玻璃",
    "desc": "浅色通透 · 毛玻璃层次",
    "swatch": [
      "#EAF2FF",
      "#1D4ED8",
      "#0E9F6E",
      "#FFC9DE"
    ]
  }
];

export const THEMES: Record<ThemeId, RnTokens> = {
  "swiss": {
    "colors": {
      "/* —— 令牌契约（每套主题都必须定义；下面这份是 swiss 默认值兜底） —— */\n  -bg": "#F1F3F5",
      "surface": "#FFFFFF",
      "surface2": "#F7F8F9",
      "border": "#E3E7EA",
      "borderStrong": "#C9D0D6",
      "text": "#0F172A",
      "text2": "#334155",
      "text3": "#5B6472",
      "onPrimary": "#FFFFFF",
      "primary": "#0F172A",
      "primarySoft": "#EDEFF2",
      "accent": "#047857",
      "accentSoft": "#ECFDF5",
      "warn": "#B45309",
      "warnSoft": "#FFFBEB",
      "danger": "#B91C1C",
      "dangerSoft": "#FEF2F2",
      "success": "#047857",
      "successSoft": "#ECFDF5",
      "info": "#1D4ED8",
      "infoSoft": "#EFF6FF",
      "navBg": "rgba(255,255,255,.96)",
      "scrim": "rgba(8,12,20,.45)",
      "swatchBorder": "rgba(0,0,0,.18)",
      "badgeText": "#FFFFFF",
      "navFg": "#5B6472",
      "navFgActive": "#0F172A",
      "bg": "#F1F3F5"
    },
    "nums": {
      "borderW": 1,
      "radiusCard": 10,
      "radiusCtl": 6,
      "radiusPill": 999,
      "shadowCardElevation": 0,
      "shadowCtlElevation": 0,
      "shadowPressElevation": 0,
      "fsH1": 24,
      "fsH2": 12,
      "gap": 12,
      "pad": 16,
      "ctlH": 44,
      "dur": 180,
      "iconStroke": 1.75,
      "shadowSheetElevation": 2
    },
    "misc": {
      "shadowcardHard": null,
      "shadowctlHard": null,
      "shadowpressHard": null,
      "glow": "none",
      "fontMono": "ui-monospace",
      "fontBody": "Plus Jakarta Sans",
      "labelTransform": "uppercase",
      "labelTracking": ".12em",
      "ease": "ease",
      "iconCap": "round",
      "clipCard": false,
      "clipCardCorner": 0,
      "shadowsheetHard": null
    }
  },
  "brutal": {
    "colors": {
      "/* —— 令牌契约（每套主题都必须定义；下面这份是 swiss 默认值兜底） —— */\n  -bg": "#F1F3F5",
      "surface": "#FFFFFF",
      "surface2": "#EFEBE0",
      "border": "#0A0A0A",
      "borderStrong": "#0A0A0A",
      "text": "#0A0A0A",
      "text2": "#2B2B2B",
      "text3": "#4A4A4A",
      "onPrimary": "#0A0A0A",
      "primary": "#FFE94A",
      "primarySoft": "#FFF7C2",
      "accent": "#285CDB",
      "accentSoft": "#E4EBFF",
      "warn": "#B45309",
      "warnSoft": "#FFF7C2",
      "danger": "#B32922",
      "dangerSoft": "#FFD9D6",
      "success": "#00764B",
      "successSoft": "#D6F5E7",
      "info": "#285CDB",
      "infoSoft": "#E4EBFF",
      "navBg": "#0A0A0A",
      "scrim": "rgba(10,10,10,.5)",
      "swatchBorder": "rgba(0,0,0,.3)",
      "badgeText": "#FFFFFF",
      "navFg": "#C9C9C9",
      "navFgActive": "#FFE94A",
      "bg": "#F4F1EA"
    },
    "nums": {
      "borderW": 3,
      "radiusCard": 0,
      "radiusCtl": 0,
      "radiusPill": 0,
      "shadowCardElevation": 8,
      "shadowCtlElevation": 6,
      "shadowPressElevation": 4,
      "fsH1": 22,
      "fsH2": 12,
      "gap": 14,
      "pad": 14,
      "ctlH": 48,
      "dur": 100,
      "iconStroke": 2.25,
      "shadowSheetElevation": 2
    },
    "misc": {
      "shadowcardHard": {
        "x": 6,
        "y": 6,
        "color": "#0A0A0A"
      },
      "shadowctlHard": {
        "x": 4,
        "y": 4,
        "color": "#0A0A0A"
      },
      "shadowpressHard": {
        "x": 2,
        "y": 2,
        "color": "#0A0A0A"
      },
      "glow": "none",
      "fontMono": "Space Mono",
      "fontBody": "Space Mono",
      "labelTransform": "uppercase",
      "labelTracking": ".14em",
      "ease": "linear",
      "iconCap": "square",
      "clipCard": false,
      "clipCardCorner": 0,
      "shadowsheetHard": null
    }
  },
  "clay": {
    "colors": {
      "/* —— 令牌契约（每套主题都必须定义；下面这份是 swiss 默认值兜底） —— */\n  -bg": "#F1F3F5",
      "surface": "#FFFDF9",
      "surface2": "#FBF5EC",
      "border": "#EFE3D4",
      "borderStrong": "#D9C9B6",
      "text": "#2F2A26",
      "text2": "#4A423B",
      "text3": "#6E645C",
      "onPrimary": "#FFFFFF",
      "primary": "#15803D",
      "primarySoft": "#D8F0DF",
      "accent": "#6252BB",
      "accentSoft": "#E6E6FA",
      "warn": "#A94E08",
      "warnSoft": "#FDF0D5",
      "danger": "#B91C1C",
      "dangerSoft": "#FBE3E1",
      "success": "#137337",
      "successSoft": "#D8F0DF",
      "info": "#1D4ED8",
      "infoSoft": "#DCEAFB",
      "navBg": "rgba(255,253,249,.97)",
      "scrim": "rgba(47,42,38,.42)",
      "swatchBorder": "rgba(0,0,0,.14)",
      "badgeText": "#FFFFFF",
      "navFg": "#6E645C",
      "navFgActive": "#15803D",
      "bg": "#F6EFE6"
    },
    "nums": {
      "borderW": 3,
      "radiusCard": 26,
      "radiusCtl": 20,
      "radiusPill": 999,
      "shadowCardElevation": 2,
      "shadowCtlElevation": 2,
      "shadowPressElevation": 2,
      "fsH1": 21,
      "fsH2": 12,
      "gap": 12,
      "pad": 18,
      "ctlH": 48,
      "dur": 220,
      "iconStroke": 1.8,
      "shadowSheetElevation": 2
    },
    "misc": {
      "shadowcardHard": null,
      "shadowctlHard": null,
      "shadowpressHard": null,
      "glow": "none",
      "fontMono": "ui-monospace",
      "fontBody": "Raleway",
      "labelTransform": "none",
      "labelTracking": ".04em",
      "ease": "cubic-bezier(.34,1.56,.64,1)",
      "iconCap": "round",
      "clipCard": false,
      "clipCardCorner": 0,
      "shadowsheetHard": null
    }
  },
  "kawaii": {
    "colors": {
      "/* —— 令牌契约（每套主题都必须定义；下面这份是 swiss 默认值兜底） —— */\n  -bg": "#F1F3F5",
      "surface": "#FFFFFF",
      "surface2": "#FFF7FA",
      "border": "#FFD1E3",
      "borderStrong": "#FFAFD0",
      "text": "#5B2340",
      "text2": "#7A3856",
      "text3": "#9A5F7B",
      "onPrimary": "#5B2340",
      "primary": "#FF6FA5",
      "primarySoft": "#FFE3EF",
      "accent": "#724BCA",
      "accentSoft": "#EFE7FF",
      "warn": "#BA3E0C",
      "warnSoft": "#FFEEDD",
      "danger": "#C2193E",
      "dangerSoft": "#FFE1E8",
      "success": "#0B7954",
      "successSoft": "#DCFCE7",
      "info": "#7C3AED",
      "infoSoft": "#EFE7FF",
      "navBg": "rgba(255,255,255,.98)",
      "scrim": "rgba(91,35,64,.42)",
      "swatchBorder": "rgba(0,0,0,.16)",
      "badgeText": "#FFFFFF",
      "navFg": "#9A5F7B",
      "navFgActive": "#C2193E",
      "bg": "#FFF1F6"
    },
    "nums": {
      "borderW": 3,
      "radiusCard": 28,
      "radiusCtl": 22,
      "radiusPill": 999,
      "shadowCardElevation": 3,
      "shadowCtlElevation": 3,
      "shadowPressElevation": 2,
      "fsH1": 23,
      "fsH2": 12,
      "gap": 12,
      "pad": 16,
      "ctlH": 48,
      "dur": 240,
      "iconStroke": 2.4,
      "shadowSheetElevation": 2
    },
    "misc": {
      "shadowcardHard": null,
      "shadowctlHard": null,
      "shadowpressHard": null,
      "glow": "none",
      "fontMono": "ui-monospace",
      "fontBody": "Nunito",
      "labelTransform": "none",
      "labelTracking": ".02em",
      "ease": "cubic-bezier(.34,1.56,.64,1)",
      "iconCap": "round",
      "clipCard": false,
      "clipCardCorner": 0,
      "shadowsheetHard": null
    }
  },
  "mecha": {
    "colors": {
      "/* —— 令牌契约（每套主题都必须定义；下面这份是 swiss 默认值兜底） —— */\n  -bg": "#F1F3F5",
      "surface": "#0E1620",
      "surface2": "#121C28",
      "border": "#1F3A4D",
      "borderStrong": "#00E5FF",
      "text": "#DCEBF5",
      "text2": "#9FC0D4",
      "text3": "#6E8FA6",
      "onPrimary": "#04121A",
      "primary": "#00E5FF",
      "primarySoft": "#0B2A33",
      "accent": "#FFB020",
      "accentSoft": "#2A1F06",
      "warn": "#FFB020",
      "warnSoft": "#2A1F06",
      "danger": "#FF4D4D",
      "dangerSoft": "#2A0E10",
      "success": "#22E08A",
      "successSoft": "#082A1E",
      "info": "#4DA3FF",
      "infoSoft": "#0A2136",
      "navBg": "rgba(14,22,32,.98)",
      "scrim": "rgba(0,0,0,.62)",
      "swatchBorder": "rgba(255,255,255,.28)",
      "badgeText": "#140000",
      "navFg": "#9FC0D4",
      "navFgActive": "#00E5FF",
      "bg": "#070B12"
    },
    "nums": {
      "borderW": 1,
      "radiusCard": 2,
      "radiusCtl": 2,
      "radiusPill": 2,
      "shadowCardElevation": 2,
      "shadowCtlElevation": 2,
      "shadowPressElevation": 4,
      "fsH1": 20,
      "fsH2": 12,
      "gap": 10,
      "pad": 14,
      "ctlH": 48,
      "dur": 120,
      "iconStroke": 1.6,
      "shadowSheetElevation": 2
    },
    "misc": {
      "shadowcardHard": null,
      "shadowctlHard": null,
      "shadowpressHard": null,
      "glow": "0 0 8px rgba(0,229,255,.55)",
      "fontMono": "Share Tech Mono",
      "fontBody": "Exo 2",
      "labelTransform": "uppercase",
      "labelTracking": ".2em",
      "ease": "cubic-bezier(.2,.9,.1,1)",
      "iconCap": "square",
      "clipCard": true,
      "clipCardCorner": 14,
      "shadowsheetHard": null
    }
  },
  "midnight": {
    "colors": {
      "/* —— 令牌契约（每套主题都必须定义；下面这份是 swiss 默认值兜底） —— */\n  -bg": "#F1F3F5",
      "surface": "#192134",
      "surface2": "#1F2942",
      "border": "rgba(255,255,255,.10)",
      "borderStrong": "rgba(255,255,255,.22)",
      "text": "#EDF1F7",
      "text2": "#C3CDDE",
      "text3": "#94A3B8",
      "onPrimary": "#0F172A",
      "primary": "#F0B44A",
      "primarySoft": "#2C2415",
      "accent": "#8E80F6",
      "accentSoft": "#231F45",
      "warn": "#F0B44A",
      "warnSoft": "#2C2415",
      "danger": "#F87171",
      "dangerSoft": "#33191C",
      "success": "#4ADE80",
      "successSoft": "#122C22",
      "info": "#7DA9FF",
      "infoSoft": "#16233D",
      "navBg": "rgba(25,33,52,.97)",
      "scrim": "rgba(0,0,0,.6)",
      "swatchBorder": "rgba(255,255,255,.22)",
      "badgeText": "#2A0B0B",
      "navFg": "#94A3B8",
      "navFgActive": "#F0B44A",
      "bg": "#0F172A"
    },
    "nums": {
      "borderW": 1,
      "radiusCard": 16,
      "radiusCtl": 12,
      "radiusPill": 999,
      "shadowCardElevation": 4,
      "shadowCtlElevation": 3,
      "shadowPressElevation": 3,
      "fsH1": 21,
      "fsH2": 12,
      "gap": 12,
      "pad": 16,
      "ctlH": 46,
      "dur": 200,
      "iconStroke": 1.9,
      "shadowSheetElevation": 2
    },
    "misc": {
      "shadowcardHard": null,
      "shadowctlHard": null,
      "shadowpressHard": null,
      "glow": "none",
      "fontMono": "Fira Code",
      "fontBody": "Fira Sans",
      "labelTransform": "none",
      "labelTracking": ".04em",
      "ease": "ease",
      "iconCap": "round",
      "clipCard": false,
      "clipCardCorner": 0,
      "shadowsheetHard": null
    }
  },
  "memphis": {
    "colors": {
      "/* —— 令牌契约（每套主题都必须定义；下面这份是 swiss 默认值兜底） —— */\n  -bg": "#F1F3F5",
      "surface": "#FFFFFF",
      "surface2": "#FFF6E8",
      "border": "#111111",
      "borderStrong": "#111111",
      "text": "#111111",
      "text2": "#333333",
      "text3": "#5A5A5A",
      "onPrimary": "#111111",
      "primary": "#FFCE5C",
      "primarySoft": "#FFF1CC",
      "accent": "#99447C",
      "accentSoft": "#FFE1F5",
      "warn": "#9C5604",
      "warnSoft": "#FFF1CC",
      "danger": "#AD3838",
      "dangerSoft": "#FFE0E0",
      "success": "#0B7954",
      "successSoft": "#DCFCE7",
      "info": "#556290",
      "infoSoft": "#E7EBF7",
      "navBg": "rgba(255,253,246,.98)",
      "scrim": "rgba(17,17,17,.5)",
      "swatchBorder": "rgba(0,0,0,.25)",
      "badgeText": "#FFFFFF",
      "navFg": "#5A5A5A",
      "navFgActive": "#111111",
      "bg": "#FFFDF6"
    },
    "nums": {
      "borderW": 3,
      "radiusCard": 4,
      "radiusCtl": 4,
      "radiusPill": 999,
      "shadowCardElevation": 10,
      "shadowCtlElevation": 7,
      "shadowPressElevation": 4,
      "fsH1": 22,
      "fsH2": 12,
      "gap": 12,
      "pad": 16,
      "ctlH": 46,
      "dur": 140,
      "iconStroke": 2.1,
      "shadowSheetElevation": 2
    },
    "misc": {
      "shadowcardHard": {
        "x": 8,
        "y": 8,
        "color": "#111111"
      },
      "shadowctlHard": {
        "x": 5,
        "y": 5,
        "color": "#111111"
      },
      "shadowpressHard": {
        "x": 2,
        "y": 2,
        "color": "#111111"
      },
      "glow": "none",
      "fontMono": "JetBrains Mono",
      "fontBody": "Inter",
      "labelTransform": "uppercase",
      "labelTracking": ".1em",
      "ease": "cubic-bezier(.2,.9,.1,1)",
      "iconCap": "round",
      "clipCard": false,
      "clipCardCorner": 0,
      "shadowsheetHard": null
    }
  },
  "glass": {
    "colors": {
      "/* —— 令牌契约（每套主题都必须定义；下面这份是 swiss 默认值兜底） —— */\n  -bg": "#F1F3F5",
      "surface": "rgba(255,255,255,.62)",
      "surface2": "rgba(255,255,255,.42)",
      "border": "rgba(255,255,255,.75)",
      "borderStrong": "rgba(255,255,255,.95)",
      "text": "#0B1B33",
      "text2": "#33506E",
      "text3": "#57708D",
      "onPrimary": "#FFFFFF",
      "primary": "#1D4ED8",
      "primarySoft": "rgba(29,78,216,.14)",
      "accent": "#0A6C4B",
      "accentSoft": "rgba(14,159,110,.16)",
      "warn": "#9E4908",
      "warnSoft": "rgba(245,158,11,.18)",
      "danger": "#B91C1C",
      "dangerSoft": "rgba(220,38,38,.14)",
      "success": "#0A6C4B",
      "successSoft": "rgba(14,159,110,.16)",
      "info": "#1D4ED8",
      "infoSoft": "rgba(29,78,216,.14)",
      "navBg": "rgba(255,255,255,.72)",
      "scrim": "rgba(11,27,51,.4)",
      "swatchBorder": "rgba(255,255,255,.8)",
      "badgeText": "#FFFFFF",
      "navFg": "#5B7593",
      "navFgActive": "#0B1B33",
      "bg": "#EAF2FF"
    },
    "nums": {
      "borderW": 1,
      "radiusCard": 20,
      "radiusCtl": 14,
      "radiusPill": 999,
      "shadowCardElevation": 4,
      "shadowCtlElevation": 3,
      "shadowPressElevation": 3,
      "fsH1": 22,
      "fsH2": 12,
      "gap": 12,
      "pad": 16,
      "ctlH": 46,
      "dur": 180,
      "iconStroke": 1.8,
      "shadowSheetElevation": 2
    },
    "misc": {
      "shadowcardHard": null,
      "shadowctlHard": null,
      "shadowpressHard": null,
      "glow": "none",
      "fontMono": "JetBrains Mono",
      "fontBody": "Inter",
      "labelTransform": "none",
      "labelTracking": ".04em",
      "ease": "cubic-bezier(.2,.9,.1,1)",
      "iconCap": "round",
      "clipCard": false,
      "clipCardCorner": 0,
      "shadowsheetHard": null
    }
  }
};
